version: '3.9'

services:
  djangoservice:
    container_name: ${CONTAINER_NAME_DJANGO}
    build:
      context: .
    ports:
      - "${DJANGO_PORT_CONTAINER}:8000" 
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./.env
    depends_on:
      - psqlservice
    networks:
      - service_network
      
  psqlservice:
    container_name: ${CONTAINER_NAME_PSQL}
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT_CONTAINER}:${POSTGRES_PORT}" 
    networks:
      - service_network


networks:
  service_network:
    driver: bridge
