version: '3.9'

services:
  djangoservice:
    container_name: djangoservice
    build:
      context: .
    ports:
      - "${DJANGO_PORT_CONTAINER}:8000" 
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./.env
    depends_on:
      - psqlservice
    networks:
      - service_network
      
  psqlservice:
    container_name: psqlservice
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT_CONTAINER}:${POSTGRES_PORT}" 
    networks:
      - service_network
  
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/web/static:/data/web/static  # Mapeamento do diretório de arquivos estáticos do Django para o Nginx
      - ./data/web/media:/data/web/media    # Mapeamento do diretório de arquivos de mídia do Django para o Nginx
      - ./data/web/static/errors:/usr/share/nginx/html/errors # Mapeamento da pasta errors como volume
      - ./certs:/etc/nginx/certs  # Mapeamento do diretório de certificados SSL
    depends_on:
      - djangoservice
    networks:
      - service_network

networks:
  service_network:
    driver: bridge
